### PR TITLE
Rust sample bot

### PR DESCRIPTION
**Pull request by JWorthe**
Evening folks

I hacked this Rust bot together. I don't have a Windows dev machine to test it on, so I figured it would be better to just get the pull request up so that I can ask for some feedback on it. It works on my (Linux) machine.

To get it running, you'll need to have the Rust build tools. There's a small readme in there with some URLs to get you started.

Let me know if anything needs fixing. I know the bot itself isn't exactly the cleanest of code.

Kind regards,
Justin

### CODE REVIEW

**Comment by EntelectChallenge** [comment]
Thanks JWorthe,

I will have a look at this over the weekend.  If we can get it working correctly then we will include this as a supported language.

**Comment by svanellewee** [comment]
Nice one Justin, i hope it works easily. I think if the Golang runner works then the Rusty one should as well since they're both native? I suspect I might still need to add some code support to my changes so I watch what happens here with interest.

**Comment by JWorthe** [comment]
Thanks Stephan. Well done on getting your Go compiler in. The new "forceRebuild" flag helped me in making sure that my bot compiler actually works as well 😂

**Comment by JWorthe** [comment]
@EntelectChallenge I saw that there were merge conflicts on this pull request. I've resolved them, and it's ready for review again.

**Pull request merged**
